### ISSUE TITLE
Bin doesn't connect to panel

### ISSUE THREAD

**Issue by Astrades** [zettabithf/LiteHTTP#3]
The title explains it almost exactly. For some reason, I can't get the bin to connect to the panel when run.

**Comment by Astrades** [comment]
It may be a port issue. What port does the bin use to connect to the panel?

**Comment by Astrades** [comment]
I'm not sure what happened, but it works now.

**Comment by diangelo911** [comment]
Having the same problem, how did you fix the issue?
