### ISSUE TITLE
Tasks not executed

### ISSUE THREAD

**Issue by Dontmindmes** [zettabithf/LiteHTTP#4]
after hours tasks are still not executed

**Comment by zettabithf** [comment]
I have just tested the bot with all commands, and they all seem to be working fine. If you are still having issues, feel free to contact me on Jabber/XMPP: zettabit@creep.im

**Comment by Dontmindmes** [comment]
https://gyazo.com/5f9f91ac4988c5c3784010022da11108

**Comment by zettabithf** [comment]
I've never had that happen before, just go ahead and email me at: zettabit@pedev.pw
