### ISSUE TITLE
Litehttp geoip error

### ISSUE THREAD

**Issue by gottembob** [zettabithf/LiteHTTP#8]
hello,

i did everything setting up litehttp and it worked but i get this problem:
Warning: A non-numeric value encountered in /storage/ssd3/864/4192864/public_html/Lit/LiteHTTP-master/Panel/inc/geo/geoip.inc on line 1536

Warning: A non-numeric value encountered in /storage/ssd3/864/4192864/public_html/Lit/LiteHTTP-master/Panel/inc/geo/geoip.inc on line 1399
and so on...
screenshot: https://media.discordapp.net/attachments/415250127477932052/452473733509283852/unknown.png?width=973&height=473
if geoip doesn't fix then i can't get bots
BTW i DON'T use a vps, i use a website

thanks

**Comment by wmdabess** [comment]
same problem i m using a website hosting and i have got this erreur 2

**Comment by gottembob** [comment]
Why did you close it, it's still not fixed

**Comment by zettabithf** [comment]
I told you to try a different version of PHP. You didn’t listen, so I closed it.

**Comment by gottembob** [comment]
Sorry, but which version of php do you recommend?
